### ISSUE TITLE
Segfault aacDecoder_Fill

### ISSUE THREAD

**Issue by VicLo2020** [mstorsjo/fdk-aac#122]
Hello.
I got a segmentation fault when called from a php.

$handle = $ffi->aacDecoder_Open(transportType::TT_MP4_ADTS,1);
...
$res = $ffi->aacDecoder_Fill($handle,  \FFI::addr($inBuffer),  \FFI::addr($buf_size), \FFI::addr($bytesValid));

Program received signal SIGSEGV, Segmentation fault.
__memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:383
383     ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S: No such file or directory.
(gdb) backtrace
#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:383
#1  0x00007ffff059774d in ?? () from /usr/lib/x86_64-linux-gnu/libfdk-aac.so
#2  0x00007ffff055b929 in ?? () from /usr/lib/x86_64-linux-gnu/libfdk-aac.so
#3  0x00007ffff052b03e in aacDecoder_Fill () from /usr/lib/x86_64-linux-gnu/libfdk-aac.so
#4  0x00007ffff3d748ee in ffi_call_unix64 () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#5  0x00007ffff3d742bf in ffi_call () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#6  0x00007ffff3aedb25 in ?? () from /usr/lib/php/20190902/ffi.so
#7  0x00005555558799dc in execute_ex ()
#8  0x000055555587a4e1 in zend_execute ()
#9  0x00005555557f3ee3 in zend_execute_scripts ()
#10 0x00005555557936b0 in php_execute_script ()
#11 0x000055555587c5f6 in ?? ()
#12 0x000055555565b91b in ?? ()
#13 0x00007ffff743909b in __libc_start_main (main=0x55555565b4d0, argc=2, argv=0x7fffffffeba8, init=<optimized out>,
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffeb98) at ../csu/libc-start.c:308
#14 0x000055555565ba7a in _start ()

**Comment by mstorsjo** [comment]
To be able to act on this, I need the input files that trigger it, and some way to reproduce it.
