### ISSUE TITLE
Assert `L_denum > (FIXP_DBL)0` failed in fDivNorm

### ISSUE THREAD

**Issue by scanlime** [mstorsjo/fdk-aac#98]
This looks a lot like issue #43, but it's not the same bug. I have a file that triggers the problem, as well as a backtrace below. 

```
micah@tuber:~$ wget -q https://diode.zone/download/videos/d9b37d15-5e13-4c63-b7a1-f3257794be0d-1080.mp4
micah@tuber:~$ ffmpeg -v 0 -i d9b37d15-5e13-4c63-b7a1-f3257794be0d-1080.mp4 audio.wav
micah@tuber:~$ file audio.wav 
audio.wav: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, stereo 48000 Hz
micah@tuber:~$ ffmpeg -i audio.wav -acodec libfdk_aac -aq 5 audio.m4a
ffmpeg version N-92343-g1052578 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --prefix=/home/micah/ffmpeg_build --pkg-config-flags=--static --extra-cflags=-I/home/micah/ffmpeg_build/include --extra-ldflags=-L/home/micah/ffmpeg_build/lib --extra-libs='-lpthread -lm' --bindir=/home/micah/bin --enable-gpl --enable-libaom --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree
  libavutil      56. 23.100 / 56. 23.100
  libavcodec     58. 36.100 / 58. 36.100
  libavformat    58. 21.100 / 58. 21.100
  libavdevice    58.  6.100 / 58.  6.100
  libavfilter     7. 43.100 /  7. 43.100
  libswscale      5.  4.100 /  5.  4.100
  libswresample   3.  4.100 /  3.  4.100
  libpostproc    55.  4.100 / 55.  4.100
Guessed Channel Layout for Input Stream #0.0 : stereo
Input #0, wav, from 'audio.wav':
  Metadata:
    encoder         : Lavf58.21.100
  Duration: 00:00:47.81, bitrate: 1536 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 48000 Hz, stereo, s16, 1536 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (pcm_s16le (native) -> aac (libfdk_aac))
Press [q] to stop, [?] for help
[libfdk_aac @ 0x564b159c29c0] VBR quality 590 out of range, should be 1-5
[libfdk_aac @ 0x564b159c29c0] Note, the VBR setting is unsupported and only works with some parameter combinations
Output #0, ipod, to 'audio.m4a':
  Metadata:
    encoder         : Lavf58.21.100
    Stream #0:0: Audio: aac (libfdk_aac) (mp4a / 0x6134706D), 48000 Hz, stereo, s16
    Metadata:
      encoder         : Lavc58.36.100 libfdk_aac
ffmpeg: libFDK/src/fixpoint_math.cpp:458: FIXP_DBL fDivNorm(FIXP_DBL, FIXP_DBL, INT*): Assertion `L_denum > (FIXP_DBL)0' failed.
Aborted

micah@tuber:~/ffmpeg_sources/ffmpeg$ cat VERSION 
N-92343-g1052578

micah@tuber:~/ffmpeg_sources/fdk-aac$ git log | head
commit 69a9b1a051bc3373d7ff3c348f99d564205af589
Author: Martin Storsjo <martin@martin.st>
Date:   Tue Oct 16 09:45:37 2018 +0300

(gdb) run -i audio.wav -acodec libfdk_aac -aq 5 audio.m4a
Starting program: /home/micah/bin/ffmpeg -i audio.wav -acodec libfdk_aac -aq 5 audio.m4a
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
ffmpeg version N-92343-g1052578 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --prefix=/home/micah/ffmpeg_build --pkg-config-flags=--static --extra-cflags=-I/home/micah/ffmpeg_build/include --extra-ldflags=-L/home/micah/ffmpeg_build/lib --extra-libs='-lpthread -lm' --bindir=/home/micah/bin --enable-gpl --enable-libaom --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --disable-stripping --disable-optimizations --enable-nonfree
  libavutil      56. 23.100 / 56. 23.100
  libavcodec     58. 36.100 / 58. 36.100
  libavformat    58. 21.100 / 58. 21.100
  libavdevice    58.  6.100 / 58.  6.100
  libavfilter     7. 43.100 /  7. 43.100
  libswscale      5.  4.100 /  5.  4.100
  libswresample   3.  4.100 /  3.  4.100
  libpostproc    55.  4.100 / 55.  4.100
Guessed Channel Layout for Input Stream #0.0 : stereo
Input #0, wav, from 'audio.wav':
  Metadata:
    encoder         : Lavf58.21.100
  Duration: 00:00:47.81, bitrate: 1536 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 48000 Hz, stereo, s16, 1536 kb/s
File 'audio.m4a' already exists. Overwrite ? [y/N] y
Stream mapping:
  Stream #0:0 -> #0:0 (pcm_s16le (native) -> aac (libfdk_aac))
Press [q] to stop, [?] for help
[New Thread 0x7ffff2fda700 (LWP 26124)]
[New Thread 0x7ffff27d9700 (LWP 26125)]
[New Thread 0x7ffff1fd8700 (LWP 26126)]
[New Thread 0x7ffff17d7700 (LWP 26127)]
[New Thread 0x7ffff0fd6700 (LWP 26128)]
[New Thread 0x7ffff07d5700 (LWP 26129)]
[New Thread 0x7fffeffd4700 (LWP 26130)]
[New Thread 0x7fffef7d3700 (LWP 26131)]
[libfdk_aac @ 0x5555590de9c0] VBR quality 590 out of range, should be 1-5
[libfdk_aac @ 0x5555590de9c0] Note, the VBR setting is unsupported and only works with some parameter combinations
Output #0, ipod, to 'audio.m4a':
  Metadata:
    encoder         : Lavf58.21.100
    Stream #0:0: Audio: aac (libfdk_aac) (mp4a / 0x6134706D), 48000 Hz, stereo, s16
    Metadata:
      encoder         : Lavc58.36.100 libfdk_aac
ffmpeg: libFDK/src/fixpoint_math.cpp:458: FIXP_DBL fDivNorm(FIXP_DBL, FIXP_DBL, INT*): Assertion `L_denum > (FIXP_DBL)0' failed.

Thread 1 "ffmpeg" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff4f5c42a in __GI_abort () at abort.c:89
#2  0x00007ffff4f53e67 in __assert_fail_base (fmt=<optimized out>, assertion=assertion@entry=0x555558191bdc "L_denum > (FIXP_DBL)0", 
    file=file@entry=0x555558191b64 "libFDK/src/fixpoint_math.cpp", line=line@entry=458, 
    function=function@entry=0x555558191c40 <fDivNorm(int, int, int*)::__PRETTY_FUNCTION__> "FIXP_DBL fDivNorm(FIXP_DBL, FIXP_DBL, INT*)") at assert.c:92
#3  0x00007ffff4f53f12 in __GI___assert_fail (assertion=0x555558191bdc "L_denum > (FIXP_DBL)0", file=0x555558191b64 "libFDK/src/fixpoint_math.cpp", line=458, 
    function=0x555558191c40 <fDivNorm(int, int, int*)::__PRETTY_FUNCTION__> "FIXP_DBL fDivNorm(FIXP_DBL, FIXP_DBL, INT*)") at assert.c:101
#4  0x0000555557509c40 in fDivNorm (L_num=46320, L_denum=-1765368925, result_e=0x7fffffffcab8) at libFDK/src/fixpoint_math.cpp:458
#5  0x00005555575bdaa8 in FDKaacEnc_IntensityStereoProcessing (sfbEnergyLeft=0x555559116850, sfbEnergyRight=0x555559117588, mdctSpectrumLeft=0x555559103be8, 
    mdctSpectrumRight=0x555559106138, sfbThresholdLeft=0x555559116670, sfbThresholdRight=0x5555591173a8, sfbThresholdLdDataRight=0x555559107ff8, 
    sfbSpreadEnLeft=0x5555591170c0, sfbSpreadEnRight=0x555559117df8, sfbEnergyLdDataLeft=0x555559105c88, sfbEnergyLdDataRight=0x5555591081d8, 
    msDigest=0x55555911e6b4, msMask=0x55555911e6b8, sfbCnt=49, sfbPerGroup=49, maxSfbPerGroup=49, sfbOffset=0x555559118a7c, allowIS=1, isBook=0x55555911e480, 
    isScale=0x55555911e570, pnsData=0x7fffffffd8b0) at libAACenc/src/intensity.cpp:755
#6  0x000055555753f2cc in FDKaacEnc_psyMain (channels=2, psyElement=0x55555909cf20, psyDynamic=0x555559116668, psyConf=0x555559118a70, 
    psyOutElement=0x55555911e6a0, pInput=0x5555590e6d40, inputBufSize=3685, chIdx=0x55555909c288, totalChannels=2) at libAACenc/src/psy_main.cpp:1188
#7  0x00005555575337de in FDKaacEnc_EncodeFrame (hAacEnc=0x55555909c260, hTpEnc=0x5555591360b0, inputBuffer=0x5555590e6d40, inputBufferBufSize=3685, 
    nOutBytes=0x7fffffffdc24, extPayload=0x5555590e6bf8) at libAACenc/src/aacenc.cpp:774
#8  0x00005555574be64a in aacEncEncode (hAacEncoder=0x5555590e6a50, inBufDesc=0x7fffffffdd30, outBufDesc=0x7fffffffdd00, inargs=0x7fffffffdcf8, 
    outargs=0x7fffffffdce0) at libAACenc/src/aacenc_lib.cpp:1944
#9  0x0000555555e0066c in aac_encode_frame (avctx=0x5555590de9c0, avpkt=0x55555909c080, frame=0x0, got_packet_ptr=0x7fffffffde98)
    at libavcodec/libfdk-aacenc.c:405
#10 0x0000555555c6d9ba in avcodec_encode_audio2 (avctx=0x5555590de9c0, avpkt=0x55555909c080, frame=0x0, got_packet_ptr=0x7fffffffde98)
    at libavcodec/encode.c:197
#11 0x0000555555c6e271 in do_encode (avctx=0x5555590de9c0, frame=0x0, got_packet=0x7fffffffde98) at libavcodec/encode.c:368
#12 0x0000555555c6e509 in avcodec_receive_packet (avctx=0x5555590de9c0, avpkt=0x7fffffffdeb0) at libavcodec/encode.c:437
#13 0x000055555568b335 in flush_encoders () at fftools/ffmpeg.c:1940
#14 0x0000555555695058 in transcode () at fftools/ffmpeg.c:4711
#15 0x000055555569572a in main (argc=8, argv=0x7fffffffe5e8) at fftools/ffmpeg.c:4898

(gdb) frame 5
#5  0x00005555575bdaa8 in FDKaacEnc_IntensityStereoProcessing (sfbEnergyLeft=0x555559116850, sfbEnergyRight=0x555559117588, mdctSpectrumLeft=0x555559103be8, 
    mdctSpectrumRight=0x555559106138, sfbThresholdLeft=0x555559116670, sfbThresholdRight=0x5555591173a8, sfbThresholdLdDataRight=0x555559107ff8, 
    sfbSpreadEnLeft=0x5555591170c0, sfbSpreadEnRight=0x555559117df8, sfbEnergyLdDataLeft=0x555559105c88, sfbEnergyLdDataRight=0x5555591081d8, 
    msDigest=0x55555911e6b4, msMask=0x55555911e6b8, sfbCnt=49, sfbPerGroup=49, maxSfbPerGroup=49, sfbOffset=0x555559118a7c, allowIS=1, isBook=0x55555911e480, 
    isScale=0x55555911e570, pnsData=0x7fffffffd8b0) at libAACenc/src/intensity.cpp:755
755	        tmp = fDivNorm(sfbEnergyLeft[sfb + sfboffs], es, &s1);
(gdb) i locals
s1 = -15
tmp = 643514225
s = -1893728256
es = -1765368925
s0 = 11
s2 = 1
sL = 11
sR = 11
inv_n = 44739243
sfb = 0
sfboffs = 48
j = 1024
scale = 1175557888
lr = 1671008068
hrrErr = {268435456, 12285857, 1323537, 268435456, 2856392, 30499, 268435456, 345011, 253642, 2398502, 79533, 268435456, 4351913, 268435456, 268435456, 
  268435456, 1519965, 827613, 217467, 268435456, 268435456, 268435456, 279128, 268435456, 2100121, 144315, 584429, 268435456, 276815, 410676, 268435456, 
  268435456, 115350, 63490, 72108, 49473, 51291, 17693, 15428, 12719, 178, 167, 134, 73, 148, 104, 77, 60, 94, 32767, 1464603809, 21845, -12640, 32767, 
  1464575847, 28, 1494318344, 1901360723, -744174304, 27}
normSfbLoudness = {96756610, 123708558, 228837919, 160802260, 145941572, 232687646, 133639722, 72577203, 55790102, 37503482, 47536500, 41533184, 45873634, 
  33837819, 26829128, 27273652, 33299310, 27333783, 27753448, 22908788, 22235808, 23465982, 24844502, 24919315, 19210091, 21107628, 20254964, 16248662, 
  13285439, 14346982, 12721459, 11755959, 10182921, 12368237, 12050176, 9190670, 9645802, 8702060, 8564975, 8420981, 24758845, 24424629, 24154325, 23910228, 
  23685415, 23517869, 23387930, 23253168, 30444281, 0 <repeats 11 times>}
realIsScale = {-7207707, 55982265, 79098195, 15590773, 17930171, 17744617, 16581175, 35139715, 34146661, 63895211, 29914356, -7350860, -74418176, 9621431, 
  8406257, -1210535, 71914709, 19860904, 23449570, 17195366, -7888239, 14381171, 19284889, 14015651, 29551358, 20499620, -28854961, 5876306, 18773755, 
  26311313, 16359487, 15706546, 36049811, 20240169, 36678812, 33966412, 28519740, 38778233, 38410928, 38474039, 18403093, 18404678, 18429061, 18428260, 
  18328645, 18355568, 18498651, 18415756, 18542311, 0 <repeats 11 times>}
isParams = {corr_thresh = 2040109440, total_error_thresh = 85899344, local_error_thresh = 21474836, direction_deviation_thresh = 1073741824, 
  is_region_min_loudness = 214748368, min_is_sfbs = 6, left_right_ratio_threshold = 1503238528}
isMask = {0 <repeats 33 times>, 1 <repeats 16 times>, 23170, -247014, 264903, -13340, 32767, -13336, 32767, -13332, 32767, 1494245688, 21845}
(gdb) 

```

**Comment by mstorsjo** [comment]
Thanks for the report, it was easy to reproduce this, and luckily the fix/workaround was pretty straightforward - it should be fixed now on the master branch.

**Comment by scanlime** [comment]
Verified fixed, thanks so much for the fast response!
